apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kevin-ruler-shared
  labels:
    app.kubernetes.io/name: adaptive-santa
    app.kubernetes.io/part-of: kevin-workspace
spec:
  storageClassName: rook-cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
