apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kevin-workspace
  labels:
    app.kubernetes.io/name: adaptive-santa
    app.kubernetes.io/part-of: kevin-workspace
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
